### ISSUE TITLE
orthophotos are not available

### ISSUE THREAD

**Issue by tsamaya** [hfu/w3w-gsi-tiles#1]
Hi
nice work with what3words API !
any chance that there is a mistake on the URL for the orthophotos ? I have only 404 response loading the tiles.
regards

**Comment by hfu** [comment]
Hi! thank you for your comment!

I have added the orthophoto layers which covers the the most part of Japan in addition to the disaster response orthophoto. In addition, I have updated the default map center to the disaster hit area. (Kumamoto city.)

The updates are ready at http://hfu.github.io/w3w-gsi-tiles/ . Please check it out!
